# Generated by Django 4.1.3 on 2022-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="loja",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
