# Generated by Django 4.1.3 on 2022-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_cpf_alter_user_loja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="loja",
            field=models.CharField(default="administrador", max_length=256),
        ),
    ]
